services:
  postgres:
    image: 'postgres:15.0'
    environment:
      - 'POSTGRES_DB=gradosytitulos'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5436:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'gius@gius.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  gradosytitulos-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start --import-realm
    container_name: gradosytitulos_keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/gradosytitulos_keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: secret
      KEYCLOAK_FRONTEND_URL: http://gradosytitulos-keycloak:8080
    volumes:
      - ./keycloak/gradtitubackup.json:/opt/keycloak/data/import/backup.json