spring:
  application:
    name: gradosytitulos

  datasource:
    url: jdbc:postgresql://localhost:5436/gradosytitulos
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:postgresql://localhost:5436/gradosytitulos
    locations: db.migration
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gradosytitulos
          jwk-set-uri: http://localhost:8080/realms/gradosytitulos/protocol/openid-connect/certs
keycloack:
   url: http://localhost:8080/realms/gradosytitulos/protocol/openid-connect/token
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: gradosytitulos
server:
  port: 9293

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
